### ISSUE TITLE
Support for Angular 2.0.0

### ISSUE THREAD

**Issue by anthony-pinskey** [gmostert/ng2-breadcrumb#10]
Any plans to support this for the new final release of Angular 2.0.0? Looks like a great module.

**Comment by gmostert** [comment]
Yup, def want to. Still need to take a look at the new 3.0.0 router, hopefully the api hasn't changed to much.

**Comment by Ragnarok99** [comment]
+1

**Comment by gmostert** [comment]
Updated to 2.0.0. It now sits snugly in a NgModule ready for consumption again.
