### ISSUE TITLE
exclude certain routes from showing breadcrumbs

### ISSUE THREAD

**Issue by malindamiller** [gmostert/ng2-breadcrumb#12]
I have a project nested in another project. My route looks like this: http://localhost:8080/app/resources/dashboard/health

but I want my breadcrumbs to just show Application Health and Monitoring (alias for "/health") I set the friendly name for "/"app" and "/resources" and "/dashboard" to empty string but I am still seeing  "////Application Health and Monitoring" 

Any suggestion how to fix this?

**Comment by gmostert** [comment]
Will prob have to update the service with an exclude path function. Before I get to that, how good is your css?

The links that are shown, are _<li>_ elements in an _<ul>_ element. You could try and target the exact items with an css selector and just make them _display:none_. The main _<ul>_ element uses a class called _breadcrumb_, so its easy to target.

**Comment by malindamiller** [comment]
So I tried to set a css selector but this is setting on the a tag, not the li tag so when i do the css "display:none" on each a tag, the backslash still exists 
    <ul class="breadcrumb">
            <li><a class = "home" role="button" (click)="navigateTo('/home')">Home</a></li>
                <li *ngFor="let url of _urls; let last = last; let i = index" [ngClass]="{'active': last}"> 
                    <a role="button" class = "breadcrumbi--{{i}}" *ngIf="!last" (click)="navigateTo(url)">{{index}}, {{friendlyName(url)}}</a>
                    <span *ngIf="last">{{friendlyName(url)}}</span>
                </li>

**Comment by malindamiller** [comment]
I have fixed this issue by changing the base href of my project for which I want to use the breadcrumbs!
