### ISSUE TITLE
Failed at the ng2-breadcrumb@0.3.0 postinstall script 'typings install'.

### ISSUE THREAD

**Issue by crebuh** [gmostert/ng2-breadcrumb#14]
Hi,

your component looks very promising to solve an ugly issue ;)

Nonetheless I've got problems installing it. I dont want to use typings in my project. Because we already schwitched to @types (https://www.npmjs.com/~types)

So is there a possiblity to use it without installing the typings or typings in general?

**Comment by gmostert** [comment]
So wait, is the above issue when you try and standalone build this comp, or when you include it in your project and compile that?
If you want to use it without typings, I guess you could try an pull in the js from the bundles folder and add require everything from there.

**Comment by crebuh** [comment]
@gmostert 

thx for the quick answer. Yes I dont wanto to compile due to the fact I dont want to work with the typings anymore. Do you have also a bundled version somewhere or do I have to bundle/compile it on my own?

**Comment by gmostert** [comment]
I see. If you do a npm install, theres a bundles folder that contains the js bundled code (its a SystemJS module).
If you need it in a different module format, then you will have to clone this repo and plug in some other build system to do that.

**Comment by crebuh** [comment]
@gmostert 

ok thx for the answer I will try to do that and let you know

**Comment by cocaux** [comment]
@gmostert I just try to install your breadcrumb using: 
`npm install ng2-breadcrumb --save`
but it fails at `typings install`. 
Please let me know how to resolve that.

**Comment by gmostert** [comment]
Well is there a specific error that gets thrown, something that can be debugged?

**Comment by AndrewMorris-2** [comment]
I received this issue as well. Just installed latest LTS Node with npm. Hope this helps in the debugging of this. 
Node: 6.9.2
npm: 3.10.9

Below is in the log where it failed: 

146817 verbose lifecycle ng2-breadcrumb@0.3.0~postinstall: CWD: C:\Users\USERNAME\Source\Repos\STUFF\node_modules\ng2-breadcrumb
146818 silly lifecycle ng2-breadcrumb@0.3.0~postinstall: Args: [ '/d /s /c', 'typings install' ]
146819 silly lifecycle ng2-breadcrumb@0.3.0~postinstall: Returned: code: 1  signal: null
146820 info lifecycle ng2-breadcrumb@0.3.0~postinstall: Failed to exec postinstall script
146821 verbose unlock done using C:\Users\USERNAME\AppData\Roaming\npm-cache\_locks\staging-f8eb1381cc555562.lock for C:\Users\USERNAME\Source\Repos\STUFF\node_modules\.staging

**Comment by AndrewMorris-2** [comment]
Ahh... After doing some digging I was missing a dependency. 

' npm install typings ' 

That is what fixed it for me.

**Comment by gmostert** [comment]
Typings have been removed all together, so this issue shouldn't be a problem anymore
