### ISSUE TITLE
add Friendly Names For Routes with parameters 

### ISSUE THREAD

**Issue by Ragnarok99** [gmostert/ng2-breadcrumb#15]
How to add friendlyNames to routes with parameters for example when I do this:

        breadcrumbService.addFriendlyNameForRoute('/comp1', 'home');

It works just perfect, but if I do this:

        breadcrumbService.addFriendlyNameForRoute('/comp1/:id', 'details');

It seems like it doesn´t work

Am I doing something wrong?

Thanks !

**Comment by gmostert** [comment]
Params arent supported, has to be the exact url for it to match. So something like:
```
breadcrumbService.addFriendlyNameForRoute('/comp1/1', 'details');
breadcrumbService.addFriendlyNameForRoute('/comp1/2', 'details');
```

**Comment by gmostert** [comment]
See https://github.com/gmostert/ng2-breadcrumb/issues/8
