### ISSUE TITLE
Property 'includes' does not exist

### ISSUE THREAD

**Issue by Helayxa** [gmostert/ng2-breadcrumb#20]
Hi,

I'm trying to use ng2-breadcrumb, but I got this error in the console :

ng2-breadcrumb\app\components\breadcrumbService.ts:90:29 
Property 'includes' does not exist on type 'string[]'

Any idea to solve this ?

Thanks in advance.

EDIT : I'm working with angular-cli. In my tsconfig.json file, in the compilerOptions, there was : 
"lib": ["es7", "dom"].
But I need to put es6 instead of es7, else my project is not working any more. With es7, no more errors for your lib, but with es6 I got the error reported below.
Can you fix this ?

**Comment by gmostert** [comment]
If I google your issue I can only find a link to the inverse of your problem (ES7 failing): [https://github.com/Microsoft/TypeScript/issues/2340](url). I personally compile to es5, and that has no issues either..

**Comment by Helayxa** [comment]
I also compile to es5...
If it can help, my tsconfig.json is here :
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}

**Comment by gmostert** [comment]
Dude, this isnt an issue I can debug. You could try using the below config, its whats working on my project:
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "es2015", "dom"],
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true,
    "typeRoots": [
      "./node_modules/@types",
      "./node_modules"
    ],
    "types": [
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "dist",
    "src"
  ],
  "compileOnSave": false
}`

**Comment by ZeeAzmat-punch** [comment]
still didn't work.
