### ISSUE TITLE
No provider for Router Error

### ISSUE THREAD

**Issue by sdornan** [gmostert/ng2-breadcrumb#21]
I followed the instructions by adding `Ng2BreadcrumbModule` and `BreadcrumbService` to `AppModule` and then added the `BreadcrumbService` to `AppComponent`.

However, when running the app I get an error:

`EXCEPTION: Error in ./AppComponent class AppComponent - inline template:0:45 caused by: No provider for Router!`

**Comment by gmostert** [comment]
It sounds like your not importing the router into your app..? Otherwise no idea..

**Comment by messerbill** [comment]
same error here, and i definitley import the router into my app...
