### ISSUE TITLE
Regex not working for strings

### ISSUE THREAD

**Issue by chrillewoodz** [gmostert/ng2-breadcrumb#23]
When I have this url: `/admin/dashboard/models-brands/9/models`

This works:

    breadcrumbs.addFriendlyNameForRouteRegex('/admin/dashboard/models-brands/[0-9]/models', 'Modeller');

These however never works if I have an url that's `/admin/dashboard/models-brands/volvo/models`:

    breadcrumbs.addFriendlyNameForRouteRegex('/admin/dashboard/models-brands/[a-z]/models', 'Modeller');

    breadcrumbs.addFriendlyNameForRouteRegex('/admin/dashboard/models-brands/[a-z0-9]/models', 'Modeller');

    breadcrumbs.addFriendlyNameForRouteRegex('/admin/dashboard/models-brands/[a-zA-Z0-9]/models', 'Modeller');

I've also tried using `^` and `$` as per the examples you've provided but it doesn't work either. 

Any idea why?

**EDIT:** I guess this is a global selector issue, how would I match more than one character here? I can't get the `/g` to work.

**Comment by gmostert** [comment]
You'll will have to write a more comprehensive regex rule to match your condition. Have a look a this tool [http://tools.netshiftmedia.com/regexlibrary/](url). If you add your regex and test it with a path like 'admin/dashboard/models-brands/1/models', it fails..

**Comment by BenjaminSymanzik** [comment]
I´m having the same issue with ng5-breadcrumb:

/publisher/detail/uu2k6b3v0au5p106l/settings

This doesnt do anything:

breadcrumbService.addFriendlyNameForRouteRegex('/publisher/detail/[a-z0-9]/settings', 'Settings')

This works:

breadcrumbService.addFriendlyNameForRouteRegex('/publisher/detail/[a-z0-9]', 'Settings')

Output:
publisher >> detail >> Settings >> Settings

So it matches when there is nothing after the regex.
