### ISSUE TITLE
Can not run with webpack?

### ISSUE THREAD

**Issue by baonguyenyam** [gmostert/ng2-breadcrumb#3]
Hi!
You missing "]" in src/breadcumb/breadcumb.ts in line 42
And 
When i run it show this error 
error TS2339: Property 'getOwnMetadata' does not exist on type 'typeof Reflect'.

**Comment by gmostert** [comment]
I updated master with the missing bracket. my bad. 
I also updated the readme to include the reflect-metadata npm library as a dependency. Its used for extracting the RouterConfig and should fix the error your getting.

**Comment by baonguyenyam** [comment]
Hj gmostert !
For this version BreadCrumb only run with 1 router-outlet, if i have multi router-outlet (children) it not working

**Comment by gmostert** [comment]
Multi router support is going to take some rethinking. Its something that I would like to support, but simply haven't got round to implementing. My initial thoughts around the matter is stated in this responce https://github.com/gmostert/ng2-breadcrumb/issues/2
