### ISSUE TITLE
Property 'includes' does not exist on type 'string[]'

### ISSUE THREAD

**Issue by ZeeAzmat-punch** [gmostert/ng2-breadcrumb#31]
breadcrumbService.ts:90:29 
breadcrumbService.ts:99:34 
breadcrumbService.ts:108:35 

    "@angular/common": "^2.0.2",
    "@angular/compiler": "^2.0.2",
    "@angular/core": "^2.0.2",
    "@angular/forms": "^2.0.2",
    "@angular/http": "^2.0.2",
    "@angular/material": "^2.0.0-alpha.9-3",
    "@angular/platform-browser": "^2.0.2",
    "@angular/platform-browser-dynamic": "^2.0.2",
    "@angular/router": "3.0.1",

Getting this error in breadcrumbservice.ts when installed ng-breadcrumb,  help would be appreciated.

**Comment by bbrink68** [comment]
You need to set `tsconfig.json` compilerOptions.lib from "es6" to "es7".

**Comment by DennisHoy** [comment]
It works if we could have line 10 and 11 in ng2-breadcrumb/app/components/breadcrumbService.ts
changed from:
private hideRoutes: Array<string> = new Array<string>();
private hideRoutesRegex: Array<string> = new Array<string>();
to:
private hideRoutes: any = new Array<string>();
private hideRoutesRegex: any = new Array<string>();

**Comment by GopiAnnan** [comment]
As @bbrink68 mentioned, I have resolved by updating tsconfig.json with following lines.
"lib": [
  "dom",
  "es7"
],
 [Reference Url] (https://github.com/AngularClass/angular2-webpack-starter/issues/931)

**Comment by gmostert** [comment]
I implemented @DennisHoy suggestion. Hope this does the trick as it should really not be necessary to compile against es7, I myself use es5.
