### ISSUE TITLE
Callback function with route parameters does not work as documented

### ISSUE THREAD

**Issue by Delta388** [gmostert/ng2-breadcrumb#35]
When I do this

    breadcrumbService.addCallbackForRoute('/home/users/1', this.getNameForUser);
    breadcrumbService.addCallbackForRouteRegex('^/home/users/[0-9]$', this.getNameForUser);

    getNameForUser(id:string):string {
        return 'specific name for user with id';
    }

C&P from the documentation, I get an error 

    Argument of type '(id: string) => string' is not assignable to parameter of type '() => string'.

Is this intentional? Looks as if the "regex"-Functions only accept parameterless functions for the callback.

**Comment by gmostert** [comment]
Nope, this is an oversight on my part, fixed in v0.5.1

**Comment by RawatNitin** [comment]
callBack functions still don't work, even in v0.5.2.
Help!
