### ISSUE TITLE
Make the 'breadcrumb' class optionally added.

### ISSUE THREAD

**Issue by TrevorBroderick1** [gmostert/ng2-breadcrumb#36]
I have bootstrap in my project, but I don't want this component to use their style. It's really annoying to need to try and overwrite every bootstrap provided style if you don't want it.

You should be able to specify if you want to use bootstrap on the directive itself.

```<breadcrumb [bootstrap]='true'></breadcrumb>```

**Comment by gmostert** [comment]
Added in 0.5.3, thnx @TrevorBroderick1
