### ISSUE TITLE
Feature: Possibility to change separator sign

### ISSUE THREAD

**Issue by jdeblander** [gmostert/ng2-breadcrumb#48]
If I look at the code, I guess the "**/**" sign between two elements of the breadcrumb isn't adjustable for the moment.
Would it be possible to change this sign as with an external input?
This way you could for example, use "**>**" or "**|**" or even "**:**" instead of "**/**"

**Comment by plastikaweb** [comment]
`// Breadcrumb styling
 //  '/' separatator 
breadcrumb {
    li {
      &:not(:last-child)::after {
        content: "\2044" 
      }
    }
}`

I've accomplish this with this simple Sass snippet. Change the `content` property with the css hex value that you prefer.
