### ISSUE TITLE
Errors while AOT-Compiling

### ISSUE THREAD

**Issue by djanesch** [gmostert/ng2-breadcrumb#52]
I got the following errors while compiling the project with AOT.
`Error at ./node_modules/ng2-breadcrumb/app/components/breadcrumbService.ts:8:46: Parameter 'string' implicitly has an 'any' type.`
`Error at ./node_modules/ng2-breadcrumb/app/components/breadcrumbService.ts:8:84: Parameter 'string' implicitly has an 'any' type.`
`Error at ./node_modules/ng2-breadcrumb/app/components/breadcrumbService.ts:9:51: Parameter 'string' implicitly has an 'any' type.`
`Error at ./node_modules/ng2-breadcrumb/app/components/breadcrumbService.ts:9:89: Parameter 'string' implicitly has an 'any' type.`
`Error at ./node_modules/ng2-breadcrumb/app/components/breadcrumbService.ts:110:39: Parameter 'value' implicitly has an 'any' type.`

I have corrected them myself but maybe you could also correct them to be in the next version.

**Comment by thinkholic** [comment]
I think PR #49 is fix for this.

**Comment by gmostert** [comment]
Fixed in v0.5.8, 
thnx @Fulminant
