### ISSUE TITLE
Does this support angular 2 version 4?

### ISSUE THREAD

**Issue by evanjmg** [gmostert/ng2-breadcrumb#53]
I tried upgrading, but noticed the router changed and the breadcrumbs module broke.

**Comment by jacobuid** [comment]
Im running into this issue too, has anybody forked this repo and fixed this yet? @gmostert

**Comment by gmostert** [comment]
Updated in 0.5.10

**Comment by evanjmg** [comment]
I'm running 0.5.10 and angular 4.0.1 I'm getting ...
<img width="753" alt="screen shot 2017-04-09 at 3 25 49 pm" src="https://cloud.githubusercontent.com/assets/9342155/24838091/ff42c3b6-1d38-11e7-9352-7e041594dffd.png">

**Comment by evanjmg** [comment]
I'm running angular 4.0.1 and 0.5.10 and getting this periodically - especially when entering a lazy loaded module - it's the same error I was getting before update. 
<img width="753" alt="screen shot 2017-04-09 at 3 25 49 pm" src="https://cloud.githubusercontent.com/assets/9342155/24838121/97f441ca-1d39-11e7-8353-d5e610e2261c.png">
