### ISSUE TITLE
Support for RC.3

### ISSUE THREAD

**Issue by prashanthcvvp** [gmostert/ng2-breadcrumb#6]
Hi Gerhard Mostert,

I have updated the repo to support for angular2.RC3. it is tested. It would be great if I could upload to your repo and create PR.

**Comment by lmkerr** [comment]
given that he hasn't updated the repo in a month, i'm wondering if he's still supporting this?

**Comment by gmostert** [comment]
Hey guys

I really wanted to wait for a non-alpha router release before updating this project again, but it seems there is enough people on rc3 to warrant it. I'm going to release v0.2.0 that should support the new rc3 alpha router.

PS: Maintaining this component is not always the #1 item on my todo list. Sometimes life happens, and there's more important things to take care of. This project came about as a need for something else I was working on at the time. Its a useful little component and I def want to see it running on an official release of angular2. I just dont always get the time to update this with every rc that drops..

**Comment by lmkerr** [comment]
thanks! no worries. thanks for the reply as well as the tool. keep up the good work.
