### ISSUE TITLE
ng2-breadcrumb integration with material design

### ISSUE THREAD

**Issue by majdix** [gmostert/ng2-breadcrumb#72]
I'm trying to use this module within my angular 4 project, as i see this is by default made to work with bootstrap .
Is there any possibilty to use material design template in the breadcrumb?

**Comment by hquangthinh** [comment]
Hi @majdix  set [useBootstrap]="false" and write some custom material style to style your breadcrumb. I'm using that approach in my current project

**Comment by majdix** [comment]
@hquangthinh thanks for your answer, well i resolved it by making a custom component extending the breadcrumb component and overrided the template. I think it's a better solution , i could rewrite the whole template and customize it as i want.
