### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by TheBurgerShot** [gmostert/ng2-breadcrumb#8]
How can one handle parameters when you want to use a fancy name.

For example:
/users/1/settings
/users/2/settings

**Comment by carlosthe19916** [comment]
+1

**Comment by gmostert** [comment]
You could map them all to a generic name. Since path params will appear in the url, its just another friendly name:

breadcrumbService.addFriendlyNameForRoute('/users/1/settings', 'Users');
breadcrumbService.addFriendlyNameForRoute('/users/2/settings', 'Users');

**Comment by maricigor** [comment]
So, if we have 1000 users in database, we should map every user to generic name?

**Comment by ragafus** [comment]
+1

**Comment by dschmitz-gsits** [comment]
+1

**Comment by gmostert** [comment]
Obviously mapping a 1000 users isnt feasible, but the component doest support variables, thus there is currently no other way. Its a nice enhancement I want to incorporate into a future release. As of right now though, thats the only option, sorry man.

**Comment by dschmitz-gsits** [comment]
That'd be a great feature to add. In general there is a lot of potential in this module if it was equipped with a few more features such as parameter support as well as custom logic for the visible route name in order to provide e.g. the name of the user as part of the breadcrumb dynamically.

**Comment by gmostert** [comment]
Updated breadcrumbService to allow mapping of routes with regex and specify a callback function to fetch names for routes with params.
