### ISSUE TITLE
Regex/:id not working

### ISSUE THREAD

**Issue by lginq** [gmostert/ng2-breadcrumb#83]
I have a route accounts/123456/overview.

When I try to match specific route with this regex to replace the id parameter with correct name:
breadcrumbService.addCallbackForRouteRegex("accounts/\d+/overview", this.getName)

I don't get anything, my callback function isn't called. 

Any help?

**Comment by lginq** [comment]
I found a solution.
The thing is you need to specify friendly name for every route.
Things I did to make this work:
 
-  breadcrumbService.addCallbackForRouteRegex("accounts/[0-9]+", this.getName);
-  breadcrumbService.addFriendlyNameForRouteRegex("accounts/[0-9+]/overview", "Overview");

**Comment by ahelord** [comment]
@lginq  how can I do this 

```
getNameForUser(id: string): string {
   let name = '';
   this.userService.getUserByIdUser(+id)
     .then(userRespond => {
       name = userRespond.first_name;
       return name
     })
 }
```
